font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

background_opacity 0.75

window_padding_width 15

hide_window_decorations yes

background #0f0f17
foreground #ffffff
cursor     #007AFF

selection_background #007AFF
selection_foreground #ffffff

color0 #151515
color8 #454545
color1 #ff3b30
color9 #ff453a
color2 #34c759
colora #2ed158
color3 #ffcc00
colorb #ffd60a
color4 #007aff
color12 #0a84ff
color5 #af52de
color13 #bf5af2
color6 #5ac8fa
color14 #64d2ff
color7 #e5e5ea
color15 #ffffff
